services:
  app:
    build: .
    container_name: mistral_app
    runtime: nvidia
    env_file:
      - .env
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./data:/data
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

