services:
  app:
    build: .
    container_name: mistral_app
    runtime: nvidia
    env_file:
      - .env
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

